--!strict

export type ClientRequest = {
	RayId: string, -- generated by the client
	MunitionName: string,
	Origin: BasePart,
	InitOriginPos: Vector3,
	InitDirection: Vector3,
}

export type ServerReplication = {
	Player: Player?,
	Team: Team?,
	RayId: string,
	MunitionName: string,
	Origin: BasePart,
	InitOriginPos: Vector3,
	InitDirection: Vector3,
}

return {}
