--!strict

export type Common = {
	InitOriginPos: Vector3,
	InitDirection: Vector3,
}

export type ClientRequest = {
	RayId: string, -- generated by the client
	MunitionName: string,
	Origin: BasePart,
	Body: Common
}

export type ServerReplication = {
	Player: Player?,
	Team: Team?,
	RayId: string,
	MunitionName: string,
	Origin: BasePart?,
	Body: Common
}

return {}
